### ISSUE TITLE
icon hover and popup zindex

### ISSUE THREAD

**Issue by chrispappas007** [ljmoser83/Toronto#13]
On the popupTinker branch. I changed the heritage popups to open and close on mouse clicks. However, I thought they needed an affordance. I keep getting an error that says setStyle is not a function. I also tinkered with the zindex to try and get the heritage popups to open above the map title but that is not working either.

**Comment by ljmoser83** [comment]
I worked on the mouseover accordance and was unable to some up with anything helpful. I merged down your branch to my local master and after working on it for a bit I pushed up what I had to the remote master for you to review. the authorship statement looks good to me. I am going to make the website live so that we have a url to submit. Unless you are dead set on it, I think we can go without the legend this time.

**Comment by chrispappas007** [comment]
got it as good as it could get
